#!/usr/bin/env python3
"""Render README.md from profile config and locally generated assets."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

from common import setup_logging
from config import (
    CANVAS_WIDTH,
    CASE_STUDIES,
    COMPANY,
    CONTACT,
    INCUBATED_AT,
    NAME,
    PUBLICATION,
    ROLE,
    ROOT,
)

logger = setup_logging("render_readme")

PROJECT_TILE_WIDTH = 406


def picture(dark: str, light: str, alt: str, width: int = CANVAS_WIDTH) -> str:
    """Return GitHub-compatible paired theme artwork."""
    safe_alt = html.escape(alt, quote=True)
    return (
        "<picture>\n"
        f'  <source media="(prefers-color-scheme: dark)" srcset="{dark}">\n'
        f'  <source media="(prefers-color-scheme: light)" srcset="{light}">\n'
        f'  <img src="{dark}" width="{width}" alt="{safe_alt}">\n'
        "</picture>"
    )


def project_tile(project: dict[str, object]) -> str:
    """Return one linked, themed project tile."""
    slug = str(project["slug"])
    name = str(project["name"])
    url = html.escape(str(project["url"]), quote=True)
    art = picture(
        f"./assets/projects/{slug}-dark.svg",
        f"./assets/projects/{slug}-light.svg",
        f"{name} — project overview",
        width=PROJECT_TILE_WIDTH,
    )
    return f'<a href="{url}">{art}</a>'


def project_grid(projects: list[dict[str, object]]) -> str:
    """Lay projects out two-up with a real gutter via an HTML table."""
    rows: list[str] = []
    for start in range(0, len(projects), 2):
        pair = projects[start : start + 2]
        cells = []
        for project in pair:
            cells.append(
                f'<td width="50%" valign="top">{project_tile(project)}</td>'
            )
        if len(pair) == 1:
            cells.append('<td width="50%"></td>')
        rows.append("<tr>\n" + "\n".join(cells) + "\n</tr>")
    body = "\n".join(rows)
    return (
        '<table width="100%" cellspacing="0" cellpadding="8">\n'
        f"{body}\n"
        "</table>"
    )


def render() -> str:
    """Compose a calm, developer-first profile README with no duplicated hero copy."""
    projects = project_grid(CASE_STUDIES)

    hero = picture(
        "./assets/hero-dark.svg",
        "./assets/hero-light.svg",
        f"{NAME}, {ROLE}",
    )
    publication = picture(
        "./assets/publication-dark.svg",
        "./assets/publication-light.svg",
        f"IEEE publication — {PUBLICATION['venue']}",
    )
    capabilities = picture(
        "./assets/capabilities-dark.svg",
        "./assets/capabilities-light.svg",
        "Engineering focus across vision, XR, and AI products",
    )
    telemetry = picture(
        "./assets/contribution-dark.svg",
        "./assets/contribution-light.svg",
        "GitHub contribution graph refreshed daily",
    )
    pub_url = html.escape(PUBLICATION["url"], quote=True)

    return f"""<div align="center">

<!--
  Generated by scripts/render_readme.py
  Edit config.py, then: python scripts/generate_all.py --skip-photo
-->

{hero}

<br>

<a href="mailto:{CONTACT["email"]}">Email</a>
&nbsp;·&nbsp;
<a href="{CONTACT["linkedin"]}">LinkedIn</a>
&nbsp;·&nbsp;
<a href="{CONTACT["github"]}">GitHub</a>
&nbsp;·&nbsp;
<a href="{CONTACT["portfolio"]}">Portfolio</a>
&nbsp;·&nbsp;
<a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a>

</div>

<br>

### Featured work

{projects}

<br>

### Publication

<a href="{pub_url}">
{publication}
</a>

<br>

### Skills

{capabilities}

<br>

### Activity

{telemetry}

<br>

<div align="center">

<sub>
Founder, <a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a>
· Incubated at {html.escape(INCUBATED_AT)}
· <a href="mailto:{CONTACT["email"]}">{html.escape(CONTACT["email"])}</a>
</sub>

</div>
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "README.md")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        content = render()
        args.output.write_text(content, encoding="utf-8")
        logger.info("wrote %s (%d bytes)", args.output, len(content))
    except OSError as exc:
        logger.error("failed to write README: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
