#!/usr/bin/env python3
"""Render README.md from profile config and locally generated assets."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

from common import setup_logging
from config import (
    CANVAS_WIDTH,
    CASE_STUDIES,
    COMPANY,
    CONTACT,
    FOUNDER_THESIS,
    FRAMEWORKS,
    HIGHLIGHTS,
    LANGUAGES,
    NAME,
    POSITIONING,
    PUBLICATION,
    RESEARCH_INTERESTS,
    ROLE,
    ROOT,
)

logger = setup_logging("render_readme")


def picture(dark: str, light: str, alt: str, width: int = CANVAS_WIDTH) -> str:
    """Return GitHub-compatible paired theme artwork."""
    safe_alt = html.escape(alt, quote=True)
    return (
        "<picture>\n"
        f'  <source media="(prefers-color-scheme: dark)" srcset="{dark}">\n'
        f'  <source media="(prefers-color-scheme: light)" srcset="{light}">\n'
        f'  <img src="{dark}" width="{width}" alt="{safe_alt}">\n'
        "</picture>"
    )


def project_block(project: dict[str, object]) -> str:
    """Return a linked, themed project card."""
    slug = str(project["slug"])
    name = str(project["name"])
    url = html.escape(str(project["url"]), quote=True)
    art = picture(
        f"./assets/projects/{slug}-dark.svg",
        f"./assets/projects/{slug}-light.svg",
        f"{name} — project overview",
    )
    return f'<a href="{url}">\n{art}\n</a>'


def render() -> str:
    """Compose the complete profile README."""
    projects = "\n\n<br>\n\n".join(project_block(project) for project in CASE_STUDIES)
    research = " · ".join(RESEARCH_INTERESTS)
    languages = " · ".join(LANGUAGES)
    frameworks = " · ".join(FRAMEWORKS)
    highlights = "\n".join(f"- {html.escape(item)}" for item in HIGHLIGHTS)

    hero = picture(
        "./assets/hero-dark.svg",
        "./assets/hero-light.svg",
        f"{NAME}, {ROLE} at {COMPANY}",
    )
    capabilities = picture(
        "./assets/capabilities-dark.svg",
        "./assets/capabilities-light.svg",
        "Focus areas across vision, XR, and AI products",
    )
    research_art = picture(
        "./assets/research-dark.svg",
        "./assets/research-light.svg",
        "Research path from computer vision to spatial UX",
    )
    telemetry = picture(
        "./assets/contribution-dark.svg",
        "./assets/contribution-light.svg",
        "GitHub contribution graph refreshed daily",
    )

    return f"""<div align="center">

<!--
  Generated by scripts/render_readme.py
  Edit config.py, then: python scripts/generate_all.py --skip-photo
-->

{hero}

<br>

{html.escape(POSITIONING)}

<sub>{html.escape(FOUNDER_THESIS)}</sub>

<br><br>

<a href="mailto:{CONTACT["email"]}">Email</a> ·
<a href="{CONTACT["linkedin"]}">LinkedIn</a> ·
<a href="{CONTACT["github"]}">GitHub</a> ·
<a href="{CONTACT["portfolio"]}">Portfolio</a> ·
<a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a>

</div>

<br>

## Selected work

{projects}

<br>

## Focus

{capabilities}

<br>

## Research path

{research_art}

<div align="center">
<sub>{html.escape(research)}</sub>
</div>

<br>

## Publication

**[{html.escape(PUBLICATION["title"])}]({PUBLICATION["url"]})**<br>
{html.escape(PUBLICATION["venue"])}

<br>

## Activity

{telemetry}

<br>

## Highlights

{highlights}

<br>

## Stack

**Languages** — {html.escape(languages)}

**Frameworks & tools** — {html.escape(frameworks)}

<br>

<div align="center">

<sub>
<a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a> ·
<a href="mailto:{CONTACT["email"]}">{html.escape(CONTACT["email"])}</a>
</sub>

</div>
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "README.md")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        content = render()
        args.output.write_text(content, encoding="utf-8")
        logger.info("wrote %s (%d bytes)", args.output, len(content))
    except OSError as exc:
        logger.error("failed to write README: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
