#!/usr/bin/env python3
"""Render README.md from profile config and locally generated assets."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

from common import setup_logging
from config import (
    CANVAS_WIDTH,
    CASE_STUDIES,
    CERTIFICATION,
    COMPANY,
    CONTACT,
    FOUNDER_THESIS,
    FRAMEWORKS,
    INCUBATED_AT,
    LANGUAGES,
    NAME,
    POSITIONING,
    PUBLICATION,
    ROLE,
    ROOT,
    SLOGANS,
)

logger = setup_logging("render_readme")


def picture(dark: str, light: str, alt: str, width: int = CANVAS_WIDTH) -> str:
    """Return GitHub-compatible paired theme artwork."""
    safe_alt = html.escape(alt, quote=True)
    return (
        "<picture>\n"
        f'  <source media="(prefers-color-scheme: dark)" srcset="{dark}">\n'
        f'  <source media="(prefers-color-scheme: light)" srcset="{light}">\n'
        f'  <img src="{dark}" width="{width}" alt="{safe_alt}">\n'
        "</picture>"
    )


PROJECT_TILE_WIDTH = 406


def project_tile(project: dict[str, object]) -> str:
    """Return one linked, themed project tile."""
    slug = str(project["slug"])
    name = str(project["name"])
    url = html.escape(str(project["url"]), quote=True)
    art = picture(
        f"./assets/projects/{slug}-dark.svg",
        f"./assets/projects/{slug}-light.svg",
        f"{name} — project overview",
        width=PROJECT_TILE_WIDTH,
    )
    return f'<a href="{url}">{art}</a>'


def project_grid(projects: list[dict[str, object]]) -> str:
    """Lay projects out two-up so the grid reads as a portfolio, not a list."""
    rows = []
    for start in range(0, len(projects), 2):
        pair = projects[start : start + 2]
        tiles = "\n".join(project_tile(project) for project in pair)
        rows.append(f'<div align="center">\n\n{tiles}\n\n</div>')
    return "\n\n<br>\n\n".join(rows)


def render() -> str:
    """Compose a developer-first profile README."""
    projects = project_grid(CASE_STUDIES)
    languages = " · ".join(LANGUAGES)
    frameworks = " · ".join(FRAMEWORKS)
    slogans = " · ".join(SLOGANS)

    hero = picture(
        "./assets/hero-dark.svg",
        "./assets/hero-light.svg",
        f"{NAME}, {ROLE}",
    )
    capabilities = picture(
        "./assets/capabilities-dark.svg",
        "./assets/capabilities-light.svg",
        "Engineering focus across vision, XR, and AI products",
    )
    telemetry = picture(
        "./assets/contribution-dark.svg",
        "./assets/contribution-light.svg",
        "GitHub contribution graph refreshed daily",
    )

    return f"""<div align="center">

<!--
  Generated by scripts/render_readme.py
  Edit config.py, then: python scripts/generate_all.py --skip-photo
-->

{hero}

<br>

**{html.escape(slogans)}**

{html.escape(POSITIONING)}

<sub>{html.escape(FOUNDER_THESIS)}</sub>

<br><br>

<a href="mailto:{CONTACT["email"]}">Email</a> ·
<a href="{CONTACT["linkedin"]}">LinkedIn</a> ·
<a href="{CONTACT["github"]}">GitHub</a> ·
<a href="{CONTACT["portfolio"]}">Portfolio</a> ·
<a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a>

</div>

<br>

## Projects

Systems I've designed, built, and shipped.

{projects}

<br>

## Publication

**[{html.escape(PUBLICATION["title"])}]({PUBLICATION["url"]})**<br>
{html.escape(PUBLICATION["venue"])} · [code](https://github.com/kenzzhood/MILES)

<br>

## Skills

{capabilities}

<br>

## Activity

{telemetry}

<br>

## Stack

**Languages** — {html.escape(languages)}

**Frameworks & tools** — {html.escape(frameworks)}

**Certification** — {html.escape(CERTIFICATION)}

<br>

<div align="center">

<sub>
Founder, <a href="{CONTACT["company"]}">{html.escape(COMPANY)}</a> ·
Incubated at {html.escape(INCUBATED_AT)}
</sub>

<br>

<sub>
<a href="mailto:{CONTACT["email"]}">{html.escape(CONTACT["email"])}</a>
</sub>

</div>
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "README.md")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        content = render()
        args.output.write_text(content, encoding="utf-8")
        logger.info("wrote %s (%d bytes)", args.output, len(content))
    except OSError as exc:
        logger.error("failed to write README: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
